version: "3.7"
services:
  springapp:
    image: chandandockerproject/spring-boot-mongo-app:VERSION
    ports:
    - 8080:8080
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=devdb
    - MONGO_DB_PASSWORD=devdb@123
    networks:
    - springappbridge
  mongo:
    image: mongo:latest
    environment:
    - MONGO_INITDB_ROOT_USERNAME=devdb
    - MONGO_INITDB_ROOT_PASSWORD=devdb@123
    networks:
    - springappbridge
    volumes:
    - mongovol:/data/db
volumes:
  mongovol:
    driver: local
networks:
  springappbridge:
    driver: bridge
